stages:
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: michael/app:v1
      registry: 127.0.0.1:34612
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
